### ISSUE TITLE
[Improvement] Change to Efficiency

### ISSUE THREAD

**Issue by BadBoyJH** [Icehawk78/FrozenCookies#133]
If object A can recoup it's chocolate faster than you can BUY object B, object A is faster, even though object B will recoup it faster than object A.

Simply put, by the time you buy object B, you'll already be better off.

Recent log states you measure how it takes to recoup chocolate, and you have an estimated time to purchase, if recoup time > purchase time, buy the first one.

**Comment by Icehawk78** [comment]
This is old enough that I'm closing this, feel free to comment if you think it's still valid, preferably giving concrete examples to show how this is more efficient.
