### ISSUE TITLE
New Idea for FrozenCookie

### ISSUE THREAD

**Issue by Sparky7491** [Icehawk78/FrozenCookies#136]
Hello, I have an idea for Frozen Cookie. I was thinking of adding another Blacklist choice called Seasons, where it will have Frozen Cookie go and buy all the seasonal upgrades.

**Comment by Icehawk78** [comment]
Given the relatively random nature of unlocking seasonal cookies, there's not a very good metric for determining what the opportunity cost of being in inefficient seasons is. As such, FC will not likely include this.
