### ISSUE TITLE
Autobuy isn't fast enough after reset

### ISSUE THREAD

**Issue by Ambeco** [Icehawk78/FrozenCookies#140]
After I do a reset, I can see that my cookie count skyrockets, and Cookie clicker is only purchasing about 10 buildings a second, and I rapidly end up with huge amounts of cookies compared to the prices of buildings for several minutes. Often, after I reset, I'll sit there and repeatedly click the Prism button so those few minutes aren't completely wasted.

As a fix, FrozenCookies should detect when it can already afford to purchase the next N things on the list, and should sub-sort those based on raw delta CPS.  This would cause it to be much more efficient during the first few minutes after a high HC reset.

**Comment by Icehawk78** [comment]
There is now a "buy all buildings up to a certain amount" hotkey in the github-hosted version of the code (the gh-pages branch) by pressing 'm'.

This is probably the most that will ever be supported.
