### ISSUE TITLE
rawgithub.com doesn't resolve, scripts should use raw.github.com

### ISSUE THREAD

**Issue by triffid** [Icehawk78/FrozenCookies#141]
Frozen Cookie won't load from the bookmark loader today.

Firebug shows that rawgithub.com fails to resolve, and various other tools agree.

Changing it to raw.github.com allows it to start loading, at least until the bookmark loader tries to load another script, then loading breaks again.

I'm busy this week, but I'll slap together a pull at some point if you don't beat me to the fix

**Comment by Icehawk78** [comment]
Please use icehawk78.github.io/FrozenCookies from now on
