### ISSUE TITLE
Greedy update purchase

### ISSUE THREAD

**Issue by norro** [Icehawk78/FrozenCookies#142]
I would like to vote for an additional option "greedy update purchase" (or similar), that buys all updates that might be not the most efficient ones but are _cheap enough_.
I am usually quite annoyed with the updates that won't be purchased at all, e.g. _Weighted sleighs_. Those don't add to my CPS, but I wouldn't might if they get purchased once the are cheaper then, say 1% of my CPS.

So, the option I vote for buys all updates that are cheaper than 1% of my CPS, except chocolate egg.

**Comment by Icehawk78** [comment]
This is outside of the scope of this project, sorry.
