### ISSUE TITLE
[Beta 1.9] FrozenCookies resets milk to 0 somewhere, potentially locking you out of kitten upgrades until a refresh.

### ISSUE THREAD

**Issue by voidlily** [Icehawk78/FrozenCookies#144]

**Comment by Icehawk78** [comment]
I need to create a 1.9 branch, as I have almost all of your fixes independently implemented, and I'd like to keep the master branch safe for the live game.

**Comment by Icehawk78** [comment]
This is now fixed with the version detection and 1.9 branch
