### ISSUE TITLE
Golden switch problem

### ISSUE THREAD

**Issue by Kidsheldon** [Icehawk78/FrozenCookies#152]
FC determines that turning on the Golden switch is efficient, but still saves up a golden cookie bank, leading me to think it's unaware that the switch disables golden cookies. Even after turning on the switch, it still keeps a 2.667 nonillion cookie bank, which is completely pointless.

**Comment by Icehawk78** [comment]
That's... surprising. I'll look into that. I assume you have the autoclicker turned off completely?

**Comment by Icehawk78** [comment]
Can you link a gist of your save? I'm having trouble getting FC to ever think the Golden Switch is worthwhile to reproduce this issue.

**Comment by Ariamaki** [comment]
So, here's a 2.0 save that reproduces it: Game believes Fabrege > Golden Switch > Glow in the Dark is the correct proceeding, even with GC autoclicks turned on. `Mnx8MTQ1NTAzMzA3ODY2NjtOYU47MTQ1NTA2NjAxOTE2MztIb3VzZSBSaXNlbmtpfMOnwr3Ciwd8Ni43MzkzODMwNzg1OTc3NTdlKzIzOzIuMDExMzU2NjA0OTM5NDY2ZSsyNTsxNDQ4MTsxNzM1MDE7MS4xODUzMzE5ODUyODA2NDg2ZSsyMzs3MTk5OzA7NDsyLjc0MjI3MDU4MDI1MDU3ODhlKzI2OzM7MDswOzA7LTE7MjQ7MDsxLjY3MzMzOTM5NDAyNDI5NjhlKzI0OzI2OzE0OzIwOzE2MDcyMzE7MTtjaHJpc3RtYXM7MS42MjE0NDk0NzU5NDUzMDRlKzIzOzY7NjQ5Njg7MjkzNzs2MjAzMTswOzA7MTg5OzMyMDstMTstMTstMTsyMDsxNTswOzA7MDt8MzU3LDcxOCw2LjE5NzQ3OTM3MTU5MjgyMmUrMjMsMDszNDEsNDk2LDEuNTMzOTU1MTU2MDYwNzM2N2UrMjIsMDszMDUsNDU1LDI2MjIxNTA1NzY1NjA0NzUwMDAwLDA7MzAwLDQ1MCw0NzQ0NzUxNDY2NjI1NzY1MDAwMDAsMDszMDAsNDUwLDE0NTMwMjQ2NjAyNTkxNDk4MDAwLDA7MjYxLDQxMSw1NjI4ODgyNDMyODI4MjIzMDAwMDAsMDsyMzIsMzgyLDQwNTgwMDA5Mjg2NTI0MjUwMDAwMCwwOzIyNywzNzcsMS41NTgyOTQ5OTEwNDkwODI1ZSsyMiwwOzIwMCwzNTAsMS40Mjk0NDM5NjI0ODEzNjU2ZSsyMiwwOzE3NiwzMjYsNC41MTY3OTAwNjc3MDA4ODk2ZSsyMSwwOzE1OSwzMDksMy41NDkyMzkxODY5MzIzMzU1ZSsyMiwwOzE1MCwzMDAsMS44NTUyNjU3MjYxOTUwMDE3ZSsyMywwOzE1MCwzMDAsNC42ODUwNzU5ODY0MDEzMzc1ZSsyMywwOzE0MywyOTQsMi4xMDA1MzA2MjM2MzY5OTVlKzI0LDA7fMOnwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8OnwrzCj8Onwr/Cv8Onwr/Cv8Onwr/Cr8OnwrPCvMOkwoDCv8Okwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cs8Onwr/Cv8OnwoDCgMOkwrDCsMOnwo/Cv8Onwr/Cv8Onwr/CvMOnwoDCgMOnwr/Cv8OnwqrCj8Onwr/Cv8Onwr/Cs8Onwr/CssOkwoDCgMOkwoDCgMOkwoDCg8Omwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8OkwoDCgMOkwr/CsMOkwrzCgMOkwrzCjMOnwr/Cv8OnwoDCg8Onwr/CgMOkwoDCjsOmwrzCv8Okwr7CrMOkwo/Cv8Onwr/CvsOnwr/Cv8OkwoDCg8Okwo/CjMOnwozCs8OkwrPCjMOnwozCs0x8w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6XCv8Kfw6fCv8KAw6TCv8K/w6fCv8K/w6fCv8K/w6fCv8Kfw6fCv8Kzw6fCv8K/w6fCv8K/w6fCgcKyw6fCvMKAw6TCgcK/w6fCs8KDw6DCsMKA%21END%21`

**Comment by Ariamaki** [comment]
Some repeated testing on my end has shown that it only believes Switch is high efficiency **until** you've clicked a Golden Cookie in your current run. As soon as you click even one, it shoots down to the 0% / Infinity segment of the chart, regardless of how it would actually impact production with your current settings.

**Comment by Icehawk78** [comment]
That's because even just Frenzy/Lucky combos are worth more than a 50% CPS bump.

I'm not certain why it thinks it's valuable before one is clicked, though.

**Comment by Ariamaki** [comment]
That makes sense as to why it's set up that way right now, but in theory it should take into account things like turning off the GC Autoclick and putting the assumed efficiency at 0%: Sometimes a player wants to not interact with GCs at all, such as when they're going to put the game offline, so turning on the switch has value there. I agree that if you're going to have GC autoclicks / click them yourself, it's going to outpace the multiplier.

**Comment by Icehawk78** [comment]
Can you verify whether this behavior still occurs for you? I updated some of the logic surrounding the banks and the golden switch.

**Comment by Ariamaki** [comment]
Nope, just popped a new ascension and the Switch was already down in the boonies before I even clicked a GC. Looks like whatever changed did the trick, or it was a more elusive bug I'm having problems reproducing without falling back to that old save... And on second check, I can no longer repro with that save either. Looks like that's taken care of!

**Comment by Kidsheldon** [comment]
Sorry I stopped paying attention to this. Here's my save. I have autoclick GCs on and calculated efficiency set to 100.
MS45MDl8fDE0NTQ1Nzk1MzYxNzE7MTQ1MjM4MzQ4MjYzMDsxNDU1NDgwNzI1MzM4OyBPcnRlaWx8w6XCssKABnwzLjM3NjIyMjQzMzc5NjE1M2UrMzI7MS4yMjU1NzQxNTQzMjMwOTQ1ZSszMzszOTQyNjsxMDc1MTsyLjA5OTY3NTU2MTk4NjcxNjRlKzMyOzM4MzswOzEyOzQuNDk1MjkyNDI1OTg2MzM2NGUrMzI7MzswOzA7MDstMTsxMjk7ODUyMTsxLjcxNjk4NTI1NDMzNTc2NzZlKzMyOzE1ODsxNDs1Njg0Ozc5NDExMTQwMzM3OzEyO2NocmlzdG1hczsxLjg2MDQ4MDA0MjQ5MjM4N2UrMzM7MTI7NzY2MDQyMTsxMjE2NjY2OzY0NDM3NTU7MDswOzMyMjsxODk7MjI2OzIyNDsyMjI7MjE7MTsxNTsxOzA7fDUwMCw4NTAsMy4wMzc4NTE0MDIwMjUwOTA1ZSsyNSwwOzQ3Myw4MjgsNi40ODM5OTYwMzkzMjg1OTZlKzIzLDA7NDQ1LDc5NSwxLjE5MTUyMjQ4NjczMDc2ODllKzI0LDA7NDI4LDc3OCw0LjA0OTU1OTczODI2MTg1MWUrMjQsMDs0MTEsNzYxLDEuNDk2NDQxMzM2NzU1MTk4ZSsyNSwwOzM5NCw3NDQsNC4yNjA3MzkwMjM1NjI5NDk0ZSsyNCwwOzM4MCw3MzAsMS43NDIxNTYwMjIxNjA2MDk0ZSsyNSwwOzM1OSw3MDksOC4xNzcwMTY0NjQ5NjIzNjVlKzI0LDA7MzM1LDY4Niw0LjAwNzYyODM2NzU1MDE3NjRlKzI0LDA7MzE2LDY2NiwyLjAxMjExODM0OTgwOTg1MjdlKzI1LDA7MzAzLDY1MywxLjA3MjkzNzE5OTU3NzI1NjFlKzI2LDA7MzAwLDY1MCw2LjUyODQxMDA0MTA0NjIzOGUrMjYsMDsyOTAsNjQwLDMuNzk5MjA4NzU4NjIxMDI4ZSsyNiwwOzI2MCw2MTYsMS45OTE3NjU3Mjk0OTIxMTI4ZSsyNywwO3zDp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wq/Dp8KzwrzDpMKMwr/DpMK/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wrPDp8K/wr/Dp8K/wr/Dp8Kzwr/Dp8K/wr/Dp8K/wr/Dp8K/wrzDp8K/wr/Dp8K/wr/Dp8Kqwo/Dp8K/wr/Dp8K/wr/Dp8K/wrLDp8K/wr/Dp8K/wr/Dp8K+wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8Kzwr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K8wr/Dp8K7wq/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wq/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr9/fMOnwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/CoMOkwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cv8Onwr/Cu8Onwr/Cv8Onwr/Cv8Onwr/Cu8Ogwr/CuA%3D%3D%21END%21

**Comment by Kidsheldon** [comment]
Sorry I stopped paying attention to this. Here's my save.
Mnx8MTQ1NDU3OTUzNjE3MTsxNDUyMzgzNDgyNjMwOzE0NTU0ODEzOTU5MDk7IE9ydGVpbHzDpcKywoAGfDMuMzc4NjU3NTgzOTQ0NDQ4ZSszMjsxLjIyNTg2NTY2NTExODc2MjVlKzMzOzM5NDU0OzEwNzU3OzIuMTAxNzYwMzA1MDU2ODUwNmUrMzI7MzgzOzA7MTI7NC40OTUyOTI0MjU5ODYzMzY0ZSszMjszOzA7MDswOy0xOzEyOTs4NTI3OzEuNzE3MjM4MzIxNTA0NzA2ZSszMjsxNTg7MTQ7NTY4ODs3OTQxMTEyMDA3NjsxMjtjaHJpc3RtYXM7MS44NjA3ODM3NDIyOTM3MDQ2ZSszMzsxMjs3NjYwNDIxOzEyMTY2NjY7NjQ0Mzc1NTswOzA7MzIyOzE4OTsyMjY7MjI0OzIyMjsyMTsxOzE1OzE7MDt8NTAwLDg1MCwxLjQ2MTY0MDc5MTE5MjIwNGUrMjYsMDs0NzMsODI4LDMuMTE5NzI4OTk0ODcyNTAyNWUrMjQsMDs0NDUsNzk1LDUuNzMyOTI2NDY1OTQ4MDU4ZSsyNCwwOzQyOCw3NzgsMS45NDg0MTcxMjY2MTM3OTZlKzI1LDA7NDExLDc2MSw3LjIwMDAyMjAyMjA0Mzk3OWUrMjUsMDszOTQsNzQ0LDIuMDUwMDI0NTUxMzM2NzA4N2UrMjUsMDszODAsNzMwLDguMzgyMjYwOTEyODA3Nzk4ZSsyNSwwOzM1OSw3MDksMy45MzQzMTM4NDAxOTM5OTdlKzI1LDA7MzM1LDY4NiwxLjkyODI0MjE0MzEyOTc5NDllKzI1LDA7MzE2LDY2Niw5LjY4MTE2NTYyNTI0NDk5ZSsyNSwwOzMwMyw2NTMsNS4xNjIzNjE3MTQ3NDQzNzk1ZSsyNiwwOzMwMCw2NTAsMy4xNDEwOTg0Nzg3NjczMjk2ZSsyNywwOzI5MCw2NDAsMS44Mjc5NjI1MTcyNDMwOTZlKzI3LDA7MjYwLDYxNiw5LjU4MzI0MDQyNzA0NTI3OGUrMjcsMDt8w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8Kvw6fCs8K8w6TCjMK/w6TCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8Kzw6fCv8K/w6fCv8K/w6fCs8K/w6fCv8K/w6fCv8K/w6fCv8K8w6fCv8K/w6fCv8K/w6fCqsKPw6fCv8K/w6fCv8K/w6fCv8Kyw6fCv8K/w6fCv8K/w6fCvsK/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCs8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/w6fCvMK/w6fCu8Kvw6fCv8K/w6fCv8K/w6fCv8K/w6fCv8Kvw6fCv8K/w6fCv8K/w6fCv8K/w6fCv8K/f3zDp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wqDDpMK/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wr/Dp8K/wrvDp8K/wr/Dp8K/wr/Dp8K/wrvDoMK/wrg%3D%21END%21
