### ISSUE TITLE
Legacy update is live

### ISSUE THREAD

**Issue by jcgoble3** [Icehawk78/FrozenCookies#154]
Is FC ready for the new version, or should I wait to update CC? I use the userscript in Firefox through Greasemonkey.

If it's not ready, what issues are left to get it working?

**Comment by jcgoble3** [comment]
I was feeling frisky, so I went ahead and updated. FC seems to be working mostly fine, including the autobuyer and autoclickers. I'll leave this open for now, but close it if you want. (I may close it later.)

**Comment by Icehawk78** [comment]
Yeah, with the version detection, everything was already to use on live. I won't likely update the version counter until a change in the live version causes a conflict with 1.905's codebase, though.

**Comment by jcgoble3** [comment]
Thanks for having everything ready to go in advance! :)
