### ISSUE TITLE
Review fcWin function

### ISSUE THREAD

**Issue by Icehawk78** [Icehawk78/FrozenCookies#155]
This might be why achievements don't get notified?

**Comment by valepakh** [comment]
Can you please at least temporary comment out setting fcWin or copy-paste current code?
The only difference between fcWin and Win is that fcWin is (trying to) log an achievement.
We could live with that but can't with the absence of achievement notifications.

**Comment by Icehawk78** [comment]
This appears to be working now. During testing, it looks like the reason I put it in was because I can't easily rewrite the function, but it needs to be rewritten so that testing buying all of the chained upgrades and the like doesn't give the user achievement spam. The issues is that the logic I was using before was wrapping it the wrong way and basically only allowed showing achievements when it autobought a building, and no other time (rather than only suppressing them when it was simulating buying the buildings).
