### ISSUE TITLE
Can't open the dragon Aura Upgrade Window/Pop-Up

### ISSUE THREAD

**Issue by hardcoregandhi** [Icehawk78/FrozenCookies#159]
I can't open the window to buy upgrades or change my aura.

IT KNOWS my mouse is there because the small white dragon background appears, but nothing can bring up the window.

**Comment by TheProgenitus** [comment]
That's because of the auto-clicker. Deactivate it or click a few times in quick succession.

**Comment by hardcoregandhi** [comment]
Even if I switch off all the Frozen Cookie Controls, I still can't open the Pop-up

**Comment by TheProgenitus** [comment]
I have this "problem" only with the auto-clicker on. It's the same behaviour with the Santa-stages.

Maybe you can have a look at the JavaScript-console of your browser and report any errors you can spot there.

**Comment by Icehawk78** [comment]
Are you running any other autoclickers? The game is unable to register two simultaneous clicks, and so as long is something is clicking on the cookie, it won't register your clicks on the Santa/Dragon upgrades.

As @TheProgenitus mentioned, with FC, all you should need to do is turn off autoclick and it will allow you to select those sections again.

**Comment by Icehawk78** [comment]
For now closing this unless it can be replicated otherwise.
