### ISSUE TITLE
There should be a way to disable the bank

### ISSUE THREAD

**Issue by luacs1998** [Icehawk78/FrozenCookies#161]
Sometimes I'm stupid. Sometimes I'm suicidal. Sometimes, I simply don't want the possible "CpS bonus" that comes from golden cookies. Sometimes I simply don't want to play in a certain way.

That aside, it should be possible to tell FrozenCookies to not save up a bank for golden cookies, and spend the cookies on buildings or upgrades instead.

Now that I've gotten that off my chest...

**Comment by Icehawk78** [comment]
Well, you technically can, if you tell FC that you never click on Golden Cookies. However, that will effectively disable it from buying **anything** that affects your GC valuations, and once unlocked will almost always buy the Golden Switch.

Beyond that, I don't plan on adding any other features to disable that.
