### ISSUE TITLE
Count manual clicks during frenzy for calculations

### ISSUE THREAD

**Issue by emerald000** [Icehawk78/FrozenCookies#164]
I have both the autoclicker and autofrenzy off. I'd really like the calculations to consider the fact that I manually click the cookie during frenzies. I can somewhat achieve this by turning on autofrenzy while not in a frenzy, but it is awkward and I don't want to turn it on during frenzies.

I suppose you could use the clicks/second of autofrenzy (and autoclicker while at it) for calculations even if they are turned off.

Thanks!

**Comment by Icehawk78** [comment]
I'm actually planning on adding something similar to this as part of the fix for issue #163, so I'm going to condense this into that issue.
