### ISSUE TITLE
Wrinkler popping no longer works

### ISSUE THREAD

**Issue by ama4tf** [Icehawk78/FrozenCookies#165]
I've noticed the auto pop wrinkler fails to actually pop any of them

**Comment by dobdob** [comment]
Is working for me.

Using Chrome.

**Comment by Icehawk78** [comment]
FC will calculate whether or not it's efficient to pop your wrinklers (ie, will it help you unlock seasonal upgrades sooner or help you buy your next upgrade fast enough that it's more efficient than just holding them). In most cases, if FC thinks you should have wrinklers out, it should rarely actually end up popping them outside of Halloween/Easter unlocks.

**Comment by ama4tf** [comment]
The only thing is that I was not in Halloween/Easter mode, it was valentine's day

**Comment by Icehawk78** [comment]
That would explain it. FC didn't think there was anything to be gained from popping wrinklers (because the CPS drain doesn't harm anything but does provide a benefit.
