### ISSUE TITLE
Feature Request: Separate Elder Pledge auto buy button

### ISSUE THREAD

**Issue by dobdob** [Icehawk78/FrozenCookies#166]
Currently the Auto buy takes care of buildings, seasons and elder pledge. It would be nice to be able to turn off auto buy for buildings, but retain auto buy for Elder Pledge and perhaps even the season of your choice. 

My example now is I want to push for Kitten Experts and then reset so I can add it to a permanent upgrade slot.

**Comment by Icehawk78** [comment]
Unfortunately, that is outside of the scope of this project and not a feature I will be adding. As always, feel free to fork the project and add it on your own, but that's not a feature I want to add myself. Sorry!
