### ISSUE TITLE
Autofrenzy is not triggered during Dragonflights.

### ISSUE THREAD

**Issue by Au-Matt** [Icehawk78/FrozenCookies#180]
Dragonflights are x1111 clicking power for 11 seconds,

**Comment by nyddogghr** [comment]
Could you be more specific ? I currently use the lase version of frozen cookies (Σ 1.9.3), I have enabled only the autoclick during frenzy, and I confirm that the big cookie is clicked during dragonflights.

**Comment by Au-Matt** [comment]
I just tested it, and it does appear to trigger. Perhaps I wasn't using the latest update. Sorry about that.
