### ISSUE TITLE
Keep enough cookies in bank for Max Lucky and Max Chain rewards

### ISSUE THREAD

**Issue by shrx** [Icehawk78/FrozenCookies#186]
Right now FC ignores the bank requirements for "Max Lucky" and "Max Chain" golden cookie rewards - it will spend all cookies available when autobuy is turned on. Is it possible to add an option for autobuy to always keep enough cookies in bank to satisfy the Max rewards requirements?

**Comment by Icehawk78** [comment]
The autobuy code uses your autoclick golden cookies setting to determine whether maintaining a chain/lucky bank is worth it - if you look at the bottom of the internal information section it shows the calculated efficiency of maintaining a bank, and only prioritizes that if it's better than the most efficient purchase.
