### ISSUE TITLE
Shimmering Veil is making me lose cookies!

### ISSUE THREAD

**Issue by lemoron** [Icehawk78/FrozenCookies#195]
I decided to buy the new Shimmering veil on Cookie clicker prestige system or whatever
basically, costs 24 hour production worth of my cookies and shiz, and gives me 50% CPS as long as I don't click, click golden cookies, etc.
basically, as long as I do absolutely anything, I get more cookies.

here's the problem, I have auto-buy + Clicking on golden cookies + auto clicks enabled.

and Frozen cookies sees shimmering Veil's 50% increase and is like "oh yeah! that's a good idea"
buys it while it's auto clicking.
instantly breaks the veil.

24 hours production worth of cookies out the window!

how do I exclude Shimmering Veil from autobuy? pls help!

**Comment by geojak** [comment]
Mtarnuhak has fixed this issue in his fork. Go check it out if you want.

We have updated some stuff in the past days in his fork. If you need help in loading the fork sent me an email: jaikobblack@googlemail.com

**Comment by geojak** [comment]
Mtarnuhal has fixed this issue in his fork. Go check it out if you want.

We have updated some stuff in the past days in his fork. If you need help in loading the fork sent me an email: jaikobblack@googlemail.com

**Comment by Icehawk78** [comment]
The fix for this has been merged in.
