### ISSUE TITLE
Wrinkler Estimates

### ISSUE THREAD

**Issue by playachronix** [Icehawk78/FrozenCookies#59]
In the FrozenCookie page it would be nice to see an estimate of what I would get if I popped all the Wrinklers right now (maybe with a button to do so).  It would be nice also to see the estimate for each wrinkler on top of each wrinkler, but the easier temporary solution might be to list each in the stats page like so:

Wrinkler 1      2.34 Qa     [Pop]
Wrinkler 2      1.42 Qa     [Pop]

**Comment by Icehawk78** [comment]
Closing this
