### ISSUE TITLE
The number formatting function just went nuts

### ISSUE THREAD

**Issue by mrbellek** [Icehawk78/FrozenCookies#66]
Uh, yeah. I'm not sure what's going on here. It seems FC tries to 'format' the numbers after the decimal point as thousands.

http://i.imgur.com/j6iWHve.png
![clipboard72](https://f.cloud.github.com/assets/1481377/1705687/9eda7dfe-60e2-11e3-9b07-3f6c2b8bf662.png)

**Comment by Icehawk78** [comment]
Closing this, reopen if it's still an issue.
