### ISSUE TITLE
Christmas update stuff

### ISSUE THREAD

**Issue by mrbellek** [Icehawk78/FrozenCookies#72]
The Christmas update went live on 20/12/2013, lots of stuff was added that FC doesn't buy/click. :) 

I thought I'd create a comprehensible overview of the todo list:
- auto-click reindeer (done, see #67)
- timer for countdown until next reindeer
- auto-upgrade Santa if not 'final Santa' level (efficiency calculation?)
- auto-buy reindeer drops
- auto-buy Santa drops

**Comment by Icehawk78** [comment]
Closing this
