### ISSUE TITLE
Wrinkler popping

### ISSUE THREAD

**Issue by pjie2** [Icehawk78/FrozenCookies#84]
1)  While collecting Hallowe'en cookies, currently you pop all wrinklers as soon as they appear.  Might it be better to allow 9 wrinklers to start feeding, and then keep popping the tenth wrinkler when it appears?  Yes, you slow the rate at which you find the cookies, but you get ~5x cookie generation from having 9 wrinklers up.

2)  Could we get a "pop wrinklers 1/day" or similar option to guard against the chance of losing them on a browser crash?  Obviously the best time to pop them would be right at the start of a Clot.

**Comment by Icehawk78** [comment]
Given that wrinklers no longer are lost upon save/reload, I'm closing this.
